### ISSUE TITLE
Modify the steam widget to match the momentum greys

### ISSUE THREAD

**Issue by Hona** [momentum-mod/website#491]
![image](https://user-images.githubusercontent.com/10430890/114285146-261be180-9a98-11eb-8589-3de68c76efd8.png)
Should become:
![image](https://user-images.githubusercontent.com/10430890/114285153-36cc5780-9a98-11eb-9b32-c1f458b3c1cd.png)
---
CSS Changes:

```css
#widget {
    border: 1px solid #202020;
    background-color: #2a2a2a;
}
```

Since the widget is an `iframe`, it might require some JS to apply the styles once the element loads.
